const {TerritoryTypeEnum} = require('../Enums');

const territories =[
    {
        "id":0,
        "name":'0',
        "capital": "City",
        "type":TerritoryTypeEnum.Land,
        "borders":[1,6],
    },
    {
        "id":1,
        "name":'1',
        "capital": "City",
        "type":TerritoryTypeEnum.Land,
        "borders":[0,7,2],
    },
    {
        "id":2,
        "name":'2',
        "capital": "City",
        "type":TerritoryTypeEnum.Land,
        "borders":[1,8,3],
    },
    {
        "id":3,
        "name":'3',
        "capital": "City",
        "type":TerritoryTypeEnum.Land,
        "borders":[2,9,4],
    },
    {
        "id":4,
        "name":'4',
        "capital": "City",
        "type":TerritoryTypeEnum.Land,
        "borders":[3,10],
    },
    {
        "id":5,
        "name":'5',
        "capital": "City",
        "type":TerritoryTypeEnum.Land,
        "borders":[6,13],
    },
    {
        "id":6,
        "name":'6',
        "capital": "City",
        "type":TerritoryTypeEnum.Land,
        "borders":[0,5,14,7],
    },
    {
        "id":7,
        "name":'7',
        "capital": "City",
        "type":TerritoryTypeEnum.Land,
        "borders":[1,6,15,8],
    },
    {
        "id":8,
        "name":'8',
        "capital": "City",
        "type":TerritoryTypeEnum.Land,
        "borders":[2,7,16,9],
    },
    {
        "id":9,
        "name":'9',
        "capital": null,
        "type":TerritoryTypeEnum.Coast,
        "borders":[3,8,17,10],
    },
    {
        "id":10,
        "name":'10',
        "capital": null,
        "type":TerritoryTypeEnum.Coast,
        "borders":[4,9,18,11],
    },
    {
        "id":11,
        "name":'11',
        "capital": null,
        "type":TerritoryTypeEnum.Coast,
        "borders":[10,18,19],
    },
    {
        "id":12,
        "name":'12',
        "capital": null,
        "country":'B',
        "type":TerritoryTypeEnum.Coast,
        "borders":[21,22,13],
    },
    {
        "id":13,
        "name":'13',
        "capital": null,
        "country":'B',
        "type":TerritoryTypeEnum.Coast,
        "borders":[5,12,22,14],
    },
    {
        "id":14,
        "name":'14',
        "capital": null,
        "type":TerritoryTypeEnum.Coast,
        "borders":[6,13,22,23,15],
    },
    {
        "id":15,
        "name":'15',
        "capital": "City",
        "type":TerritoryTypeEnum.Land,
        "borders":[7,14,24,16],
    },
    {
        "id":16,
        "name":'16',
        "capital": "City",
        "type":TerritoryTypeEnum.Land,
        "borders":[8,15,25,17],
    },
    {
        "id":17,
        "name":'17',
        "capital": null,
        "type":TerritoryTypeEnum.Coast,
        "borders":[9,16,26,18],
    },
    {
        "id":18,
        "name":'18',
        "capital": null,
        "type":TerritoryTypeEnum.Sea,
        "borders":[11,10,9,17,26,27,28,19],
    },
    {
        "id":19,
        "name":'19',
        "capital": null,
        "type":TerritoryTypeEnum.Coast,
        "borders":[11,18,28,20],
    },
    {
        "id":20,
        "name":'20',
        "capital": "City",
        "type":TerritoryTypeEnum.Land,
        "borders":[19,22],
    },
    {
        "id":21,
        "name":'21',
        "capital": null,
        "type":TerritoryTypeEnum.Coast,
        "borders":[12,30,22],
    },
    {
        "id":22,
        "name":'22',
        "capital": null,
        "type":TerritoryTypeEnum.Sea,
        "borders":[14,13,12,21,30,31,32,23],
    },
    {
        "id":23,
        "name":'23',
        "capital": null,
        "type":TerritoryTypeEnum.Coast,
        "borders":[14,22,32,24],
    },
    {
        "id":24,
        "name":'24',
        "capital": null,
        "type":TerritoryTypeEnum.Coast,
        "borders":[15,23,32,33,25],
    },
    {
        "id":25,
        "name":'25',
        "capital": "City",
        "type":TerritoryTypeEnum.Land,
        "borders":[16,24,34,26],
    },
    {
        "id":26,
        "name":'26',
        "capital": null,
        "type":TerritoryTypeEnum.Coast,
        "borders":[17,25,35,27],
    },
    {
        "id":27,
        "name":'27',
        "capital": null,
        "type":TerritoryTypeEnum.Coast,
        "borders":[18,26,36,28],
    },
    {
        "id":28,
        "name":'28',
        "capital": null,
        "type":TerritoryTypeEnum.Coast,
        "borders":[19,27,37,29],
    },
    {
        "id":29,
        "name":'29',
        "capital": "City",
        "type":TerritoryTypeEnum.Land,
        "borders":[20,28,38],
    },
    {
        "id":30,
        "name":'30',
        "capital": null,
        "type":TerritoryTypeEnum.Coast,
        "borders":[22,21,31],
    },
    {
        "id":31,
        "name":'31',
        "capital": null,
        "type":TerritoryTypeEnum.Coast,
        "borders":[22,30,39,32],
    },
    {
        "id":32,
        "name":'32',
        "capital": null,
        "type":TerritoryTypeEnum.Sea,
        "borders":[24,23,22,31,39,40,41,33],
    },
    {
        "id":33,
        "name":'33',
        "capital": null,
        "type":TerritoryTypeEnum.Coast,
        "borders":[24,32,41,34],
    },
    {
        "id":34,
        "name":'34',
        "capital": null,
        "type":TerritoryTypeEnum.Coast,
        "borders":[25,33,41,42,35],
    },
    {
        "id":35,
        "name":'35',
        "capital": "City",
        "type":TerritoryTypeEnum.Land,
        "borders":[26,34,43,36],
    },
    {
        "id":36,
        "name":'36',
        "capital":"City",
        "type":TerritoryTypeEnum.Land,
        "borders":[27,35,44,37],
    },
    {
        "id":37,
        "name":'37',
        "capital": "City",
        "type":TerritoryTypeEnum.Land,
        "borders":[28,36,45,38],
    },
    {
        "id":38,
        "name":'38',
        "capital": "City",
        "type":TerritoryTypeEnum.Land,
        "borders":[29,37],
    },
    {
        "id":39,
        "name":'39',
        "capital": null,
        "type":TerritoryTypeEnum.Coast,
        "borders":[32,32,40],
    },
    {
        "id":40,
        "name":'40',
        "capital": null,
        "type":TerritoryTypeEnum.Coast,
        "borders":[32,39,46,41],
    },
    {
        "id":41,
        "name":'41',
        "capital": null,
        "type":TerritoryTypeEnum.Sea,
        "borders":[34,33,32,40,46,47,48,42],
    },
    {
        "id":42,
        "name":'42',
        "capital": null,
        "type":TerritoryTypeEnum.Coast,
        "borders":[34,41,48,43],
    },
    {
        "id":43,
        "name":'43',
        "capital": null,
        "type":TerritoryTypeEnum.Land,
        "borders":[35,42,49,44],
    },
    {
        "id":44,
        "name":'44',
        "capital": "City",
        "type":TerritoryTypeEnum.Land,
        "borders":[36,43,50,45],
    },
    {
        "id":45,
        "name":'45',
        "capital": null,
        "type":TerritoryTypeEnum.Land,
        "borders":[37,44],
    },
    {
        "id":46,
        "name":'46',
        "capital": null,
        "type":TerritoryTypeEnum.Coast,
        "borders":[41,40,47],
    },
    {
        "id":47,
        "name":'47',
        "capital": null,
        "type":TerritoryTypeEnum.Coast,
        "borders":[41,46,48],
    },
    {
        "id":48,
        "name":'48',
        "capital": null,
        "type":TerritoryTypeEnum.Coast,
        "borders":[42,41,47,49],
    },
    {
        "id":49,
        "name":'49',
        "capital": "City",
        "type":TerritoryTypeEnum.Land,
        "borders":[43,48,50],
    },
    {
        "id":50,
        "name":'50',
        "capital": "City",
        "type":TerritoryTypeEnum.Land,
        "borders":[44,49],
    }
];

module.exports = JSON.stringify(territories);